In [1]:
from sklearn.preprocessing import OneHotEncoder
import numpy as np
import nltk

sentence = 'a man eat food'

# Tokenization
data = nltk.word_tokenize(sentence)

# Reshape the data because OneHotEncoder expects a 2D array
data_reshaped = np.array(data).reshape(-1, 1)

# Initialize and fit the encoder
enc = OneHotEncoder()
enc.fit(data_reshaped)

# Transform the data
encoded_data = enc.transform(data_reshaped).toarray()

print(encoded_data)


[[1. 0. 0. 0.]
 [0. 0. 0. 1.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]]


In [2]:
from sklearn.feature_extraction.text import CountVectorizer
cv=CountVectorizer()

data=["good boy", 'good girl', 'boy girl good']

# applied BOW
cv_encoded_data = cv.fit_transform(data).toarray()
print(cv_encoded_data)

[[1 0 1]
 [0 1 1]
 [1 1 1]]


In [1]:
from sklearn.feature_extraction.text import TfidfVectorizer
tf_idf=TfidfVectorizer()

data_ = ["good boy", 'good girl', 'boy girl good']

tfidf = tf_idf.fit_transform(data_).toarray()
print(tfidf)

[[0.78980693 0.         0.61335554]
 [0.         0.78980693 0.61335554]
 [0.61980538 0.61980538 0.48133417]]


In [2]:
from sklearn.feature_extraction.text import TfidfVectorizer

data_ = ["good boy", 'good girl', 'boy girl good']

# Initialize TF-IDF vectorizer
tfidf_vectorizer = TfidfVectorizer()

# Fit and transform the data
tfidf_matrix = tfidf_vectorizer.fit_transform(data_)

# Get feature names
feature_names = tfidf_vectorizer.get_feature_names_out()

# Convert TF-IDF matrix to array
tfidf_array = tfidf_matrix.toarray()

# Print feature names and corresponding TF-IDF values
for i, doc in enumerate(data_):
    print(f"Document {i+1}:")
    for j, feature in enumerate(feature_names):
        print(f"{feature}: {tfidf_array[i][j]}")


Document 1:
boy: 0.7898069290660905
girl: 0.0
good: 0.6133555370249717
Document 2:
boy: 0.0
girl: 0.7898069290660905
good: 0.6133555370249717
Document 3:
boy: 0.6198053799406072
girl: 0.6198053799406072
good: 0.48133416873660545
